spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
azure:
  document:
    endpoint: https://your-form-recognizer.cognitiveservices.azure.com/
    api-key: your-form-recognizer-key
  blob:
    endpoint: https://your-storage-account.blob.core.windows.net/
    container-name: your-container
aws:
  s3:
    bucket-name: your-bucket
